### ISSUE TITLE
Terminal client connection fail.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-machine-exec#20]
In case if output contains not UTF-8 character websocket connection fail. We should send only UTF-8 characters for kubernetes implementation, like it was implemented for docker infra.

WebSocket connection to 'ws://serverw7v2gch0-ws-che-machine-exec-server-4444.192.168.99.100.nip.io/attach/2?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlYzdteHQ1OW94Zzg4M3ZsNSJ9.eyJ3c2lkIjoid29ya3NwYWNlYzdteHQ1OW94Zzg4M3ZsNSIsInVpZCI6ImVjYWQ4YjM3LWNkMWUtNDBlYS1hYzJiLTU3OWRkZjNkMGUwZCIsImF1ZCI6IndvcmtzcGFjZWM3bXh0NTlveGc4ODN2bDUiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE1ODE1MDI3NzMsImlhdCI6MTU0OTk2Njc3MywianRpIjoiM2M1N2Y5MmUtYjZkZS00YjU0LWFjYjAtNTc1YTg3ZThmYzZkIn0.wy5R4OQA3rcAqDNKV-H1GZWf6LSLfV4ImBkMhYqYiAmrMjpu1x4wXODu7yGqDGfXah9WXFKO7X03h-S-UxTGPNOf6V-pxCuiTJGtFbHUQwhJ2Vw38ywbIjwD7S1qRdvbxbi4bOXzPtYzWNTm_HKUk7YWhhQ6j1d4KDpZ5zSFMz4vqZqrT7VlMSS2hMuxo1mPsoy0LwpCNZs75aDgQA1Wir7J6DukaRjoofjDJPsQO1TRmE9kir39W5XgiZvC3jBcEMARRvXvk0MQPuvmrYqF36vUq6Tyght_r5q9ZCKlhFpMWhKN1Xc0Zi89sQog7wfPeGvrkuOzouEKfcpBJP22vw' failed: Could not decode a text frame as UTF-8.

**Comment by mmorhun** [comment]
Found [this](https://github.com/eclipse/che-machine-exec/issues/30) problem while tried to test utf-8 filter in real workspace with binary files.

**Comment by mmorhun** [comment]
Fixed
