### ISSUE TITLE
Add shell probe

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-machine-exec#7]
We should create "shell probe". For example if container doesn't has shell "/bin/bash" we can try to create new one exec with "/bin/sh" and so on... We can have list of such kind of "probes".

**Comment by benoitf** [comment]
maybe check as well /etc/passwd that defines shell per users

**Comment by AndrienkoAleksandr** [comment]
We should get info "about shell" from predefined places ("/etc/passwd"),  if we have no info about shell in container we can guess to prevent fail terminal creation.
